name: PR Template Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-template:
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate PR Template
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || '';
            
            // Check required sections exist
            const requiredSections = ['## PR Description', '## Changes Made', '## Reason for Change'];
            const missingSections = requiredSections.filter(section => !prBody.includes(section));
            
            // Check at least one type is selected
            const hasSelectedType = prBody.includes('- [x]');
            
            // Fail if validation errors
            const errors = [];
            if (missingSections.length > 0) {
              errors.push(`Missing sections: ${missingSections.join(', ')}`);
            }
            if (!hasSelectedType) {
              errors.push('No type selected');
            }
            
            if (errors.length > 0) {
              core.setFailed(`PR template validation failed: ${errors.join('; ')}`);
            }
